title: Student
baseurl: ""

markdown: kramdown
ins_logo: "./ucas.png"

tracking_id: #

footer: yes
footer_text: "个人主页"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Contact"
   link: "contact"
 - name: "Photos"
   link: "photo"
 - name: "Resume"
   link: "resume.pdf"
